included:
  - Quran

disabled_rules:
  - cyclomatic_complexity
  - colon

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - number_separator
  - object_literal
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing

type_name:
  max_length: 60
  
variable_name:
  min_length: 1
  max_length: 60
  
file_length: 600

line_length: 150 # Needs to configure it correctly!

type_body_length: 300 

function_parameter_count: 10

function_body_length: 80

large_tuple: 4
